#!/usr/bin/env bash

# Download the image
cd ~/Documents/
curl -O https://raw.githubusercontent.com/amrwc/derulo/master/assets/derulo.jpg

# Set the wallpaper on every screen currently visible
# Source: https://www.addictivetips.com/mac-os/change-desktop-wallpaper-with-light-and-dark-mode-on-macos-mojave/
osascript -e '
tell application "System Events"
  tell appearance preferences
    tell application "System Events"
      tell every desktop
        set picture to "~/Documents/derulo.jpg"
      end tell
    end tell
  end tell
end tell'

# Clean up
rm -f ~/Documents/derulo.jpg
printf "\033c"
