#!/usr/bin/env bash

# Give your co-workers a quick information security lesson by derulo'ing them.
# Maybe next time they will remember to lock their machine.
# 
# What?
# The script instantly changes the desktop's background of the machine it's run
# on.
# 
# Why?
# If your workplace is friendly enough to pull off pranks and some of you care
# about information security, the one and only Jason Derulo will be a perfect
# reminder of how quickly damage can be done and that an unattended computer
# should be locked.
# 
# NOTE: The script is Mac-specific – it uses snippets of AppleScript.
# 
# Usage:
# bash <(curl -s derulo.me/mac)
# 
# or:
# curl -s derulo.me/mac | bash -s
# 
# Custom image:
# curl -s derulo.me/mac | bash -s <url_to_img>

# Store the URL passed as an argument
customImgUrl="${1}"

# Generate a UUID for the image name -- when an image with the same file name
# is picked, the background won't change. Using a unique name every time solves
# the problem.
# Source: https://serverfault.com/a/799198
imgName="$(od -x /dev/urandom | head -1 | awk '{OFS="-"; print $2$3,$4,$5,$6,$7$8$9}')"

destination="${HOME}/Downloads/derulo"
# Make a temporary location and go there
mkdir -p "${destination}" && cd "${destination}"

if [[ -n "${customImgUrl}" ]]; then
	# Download the supplied image
	curl -o "${imgName}" "${customImgUrl}"
else
	images=(
		[0]="https://i.ytimg.com/vi/YBWgqb3KIeA/maxresdefault.jpg"
		[1]="http://img.wennermedia.com/social/jason-derulo-zoom-f3ecf1b6-aef2-4e91-87ef-1828c48241f2.jpg"
		[2]="http://headlineplanet.com/home/wp-content/uploads/2017/03/Jason-Derulo-WBR-2.jpg"
		[3]="http://www.jasonderulo.com/sites/g/files/g2000004951/f/201506/interior_news_bg_1.jpg"
		[4]="https://wallpapercave.com/wp/wc1689784.jpg"
	)
	# Get random number between 0 and 4 inclusive
	rand=$((RANDOM % 5))
	# Download a random image
	curl -o "${imgName}" "${images[${rand}]}"
fi

# Set the wallpaper
# Source: https://www.addictivetips.com/mac-os/change-desktop-wallpaper-with-light-and-dark-mode-on-macos-mojave/
osascript -e '
tell application "System Events"
	tell appearance preferences
		tell application "System Events"
			tell every desktop
				set picture to "'${destination}/${imgName}'"
			end tell
		end tell
	end tell
end tell'

# Clean up
cd "${HOME}" && rm -rf "${destination}" && printf "\033c"
