#!/usr/bin/env bash

# Give your co-workers a quick information security lesson by derulo'ing them.
# Maybe next time they will remember to lock their machine.
# 
# What?
# The script instantly changes the desktop's background of the machine it's run on.
# 
# Why?
# If your workplace is friendly enough to pull off pranks on each other and
# some of you care about information security, the one and only Jason Derulo
# will be a perfect reminder that an unattended computer should be locked.
# 
# Mac-specific; using snippets of AppleScript
# 
# Usage:
# bash <(curl -s derulo.me/mac)

# Define an array of image URLs
images=(
  [0]=https://i.ytimg.com/vi/YBWgqb3KIeA/maxresdefault.jpg
  [1]=http://img.wennermedia.com/social/jason-derulo-zoom-f3ecf1b6-aef2-4e91-87ef-1828c48241f2.jpg
  [2]=http://headlineplanet.com/home/wp-content/uploads/2017/03/Jason-Derulo-WBR-2.jpg
  [3]=http://www.jasonderulo.com/sites/g/files/g2000004951/f/201506/interior_news_bg_1.jpg
  [4]=https://wallpapercave.com/wp/wc1689784.jpg
)

# Generate a UUID for the image name
# NOTE: When an image with the same file name as the current desktop background
#       is picked, the background won't change. Using a unique name every time
#       solves the problem.
# NOTE: The lack of file extension seems not to be an issue.
# Source: https://serverfault.com/a/799198
imgName="$(od -x /dev/urandom | head -1 | awk '{OFS="-"; print $2$3,$4,$5,$6,$7$8$9}')"

# Make a temporary location and go there
mkdir ~/Downloads/derulo-me && cd ~/Downloads/derulo-me

# Store the URL passed as an argument
customImgUrl="$1"

# If customImg is not empty...
if [[ -n "$customImgUrl" ]]; then
  # Download the image and name it accordingly
  curl -o "$imgName" "$customImgUrl"
else
  # Get random number between 0 and 4 inclusive
  rand=$((RANDOM % 5))

  # Download a random image and name it accordingly
  curl -o "$imgName" ${images[$rand]}
fi

# Set the wallpaper on every screen currently visible
# Source: https://www.addictivetips.com/mac-os/change-desktop-wallpaper-with-light-and-dark-mode-on-macos-mojave/
osascript -e '
tell application "System Events"
  tell appearance preferences
    tell application "System Events"
      tell every desktop
        set picture to "~/Downloads/derulo-me/'$imgName'"
      end tell
    end tell
  end tell
end tell'

# Clean up
cd ~/ && rm -rf ~/Downloads/derulo-me && printf "\033c"
